### PR TITLE
Make `of_len` work, and add tests.

### PR DESCRIPTION
**Pull request by GrahamDennis**

### CODE REVIEW

**Comment by GrahamDennis** [comment]
Ping!  Also fixed tests in `close_to`, and some warnings in other tests.

**Comment by carllerche** [comment]
Sorry for the delay! I lost track of this :frowning: I suck

**Comment by carllerche** [comment]
It looks like it doesn't merge anymore :( Sorry about letting this PR stagnate

**Comment by carllerche** [comment]
I'm going to try to manually apply what matters here

**Comment by carllerche** [comment]
A lot of this PR is based on things that have changed in std (like the num traits are gone). I'll have to think more about how to fix it up.

**Comment by GrahamDennis** [comment]
I've updated this now.  This was the core of the PR.

**Comment by carllerche** [comment]
Thanks. Merged here: b61fef3e6d47114f86e5e16e26f7013e9fa8071e

I removed the suffix on the integers in the tests since this isn't supported anymore (as of the beta).

**Pull request closed without merging**
